name: sample-github-acions
on: workflow_dispatch
jobs:
  first_job:
    runs_on: ubuntu:latest
    steps:
    - name: First step
      run: echo "Hello"
    - name: second step
      run: echo "Done"
